### ISSUE TITLE
#10 Создание  двух леблов  "Inprogress"  и "Done"

### ISSUE THREAD

**Issue by yuraefremov** [nirudef/as_crm#10]
**Конечный результат:**  Создание  лейблов  "Inprogress" и "Done"
**План решения:**   Содаем в гит хабе   в  Issues 
 лейбл  с названием "inprogress" и лабел  с названием "Done" 

**Мотивация:** 
Для чего это?
Я вижу так: капитан, определяет исполнителя тикета. Исполнитель, приступая к работе, отмечает In progress, а когда выполнит, отмечает Done.
Капитан, увидев, статус Done на тикета, проверяет исполнение и сам, после проверки закрывает тикет.
Плюсы: В истории тикета легко можно посчитать сколько времени исполнитель потратил на задачу, т.е. в истории тикета видно, кто и когда присвоил лейбл тикету. Ну и будет вестись проверка результата.
**Критерий приемки:**  Проверка при начале  работы над тикетом  лабел "Inprogress" . при завершении работы над тикетом, перед тем как закрыть, "Done"

**Comment by Aseliya** [comment]
Лейбл "Done" и "In progress" созданы.
