### ISSUE TITLE
Создание меню с вкладками для Админа  на странице Группы

### ISSUE THREAD

**Issue by elenanikiforova30031979** [nirudef/as_crm#101]
Конечный результат:
На страницы Группы  создать  меню с вкладками  "Занятия", "Домашки", "Успеваемость"  
План решения:
можно просмотреть занятие № 15 https://docs.google.com/document/d/16N5PGLGF9XvNAr0DWnHajfMMb0s0zevzrACnPM0QF28/edit,
 а также прописать в views/admin/courses/show.html.erb   "Занятия", "Домашки", "Успеваемость"   При необходимости недостающие вьюхи  добавить и внести правки в соответствующие контроллеры.

Мотивация:
Желание Заказчика

Критерий приемки:
Проверка наличия   панели  меню с вкладками Группы.

**Comment by nirudef** [comment]
**Планируемое время работы:** 30 минут

**Comment by nirudef** [comment]
**Затраченное время:** 30 минут
