### ISSUE TITLE
#2 Создать пустое приложение

### ISSUE THREAD

**Issue by nirudef** [nirudef/as_crm#2]
Конечный результат:
Создать пустое приложение.

План решения:

Мотивация:
Задача от наставника: один из разработчиков должен взять на себя задачу создания пустого приложения.

Критерии приемки:

Планируемой время работы:
1 час

**Comment by Aseliya** [comment]
Пустое приложение создано на ветке dev.

**Comment by nirudef** [comment]
Наставник говорит:
насчет репозитория, у вас разошелся мастер с девом, сейчас мастер пустой, потому что Асель удалила все из-за некорректного объявления корневого каталога, а в дев она повторила эту ошибку и опять создала корневой каталог, аналитику надо принять это во внимание, для этого надо вернуть тикет по созданию пустого проекта назад Асель. Решение для Асель: скопируйте все из вашей текущей папку crm_app (если не ошибаюсь) на каталог выше, там где лежит папочка .git удалите старый корневой каталог (crm_app) и закоммитте/пуште эти изменения

**Comment by yuraefremov** [comment]
Наставник говорит:
насчет репозитория, у вас разошелся мастер с девом, сейчас мастер пустой, потому что Асель удалила все из-за некорректного объявления корневого каталога, а в дев она повторила эту ошибку и опять создала корневой каталог, аналитику надо принять это во внимание, для этого надо вернуть тикет по созданию пустого проекта назад Асель. Решение для Асель: скопируйте все из вашей текущей папку crm_app (если не ошибаюсь) на каталог выше, там где лежит папочка .git удалите старый корневой каталог (crm_app) и закоммитте/пуште эти изменения

**Comment by Aseliya** [comment]
Ветка dev удалена. Пустое приложение "залито" в ветку master.
