### ISSUE TITLE
Создание таблицы Course

### ISSUE THREAD

**Issue by yuraefremov** [nirudef/as_crm#25]
**Конечный результат:**
Создать  модель  Course

**План решения:**  
Генерируем модель  Course  с  полем  name:string 
делаем CRUD для Админа
Создаем контроллер admin/courses_controller 
Создаем вьюхи  admin (index, show, edit, update, delete)
Настраиваем роутинг для  админа

**Мотивация:** 
в таблице студен есть поле course_id на который записан студент.

**Критерий приемки:**  
Проверка  таблицы, создание  курса,  проверка у студента куда записался студент

**Comment by elenanikiforova30031979** [comment]
созданы заново модель group с контроллерами  для админа (crud) и вьюхи, и контроллер не админский с show, сиды

**Comment by elenanikiforova30031979** [comment]
по времени выполнения: если бы сразу добавила все поля, а не исправляла то - 30 мин.

**Comment by elenanikiforova30031979** [comment]
связь установлена

**Comment by elenanikiforova30031979** [comment]
исправлен контроллер

**Comment by yuraefremov** [comment]
Попробовал после  "Fix conflict". Результат остался прежним. Исправляйте.

**Comment by nirudef** [comment]
**Затраченное время:** 10 минут
