### ISSUE TITLE
Создание  модели Группа 

### ISSUE THREAD

**Issue by yuraefremov** [nirudef/as_crm#26]
**Конечный результат:** 
Создать модель Group

**План решения**: 
Генерируем модель Group с полями 
name:string
course_id:integer
Устанавливаем связь с моделью Course
делаем CRUD для Админа
Создаем контроллер admin/groups_controller
Создаем вьюхи admin(index, show, edit, update, delete)
Настраиваем роутинг для админа

**Мотивация:** 
в таблице студент есть поле группы на которую записан студент.

**Критерий приемки:**
 Проверка таблицы, создание групы, проверка у студента куда записался  в какую группустудент

**Comment by Aseliya** [comment]
У модели Group должны быть поля "Дата начала" и "Дата окончания"

**Comment by elenanikiforova30031979** [comment]
планируемое время выполнения 1 час

**Comment by elenanikiforova30031979** [comment]
сделаны все контроллеры с вьюхами. остальное завтра

**Comment by elenanikiforova30031979** [comment]
по времени выполнения: если бы сразу добавила все поля, а не исправляла то - 30 мин

**Comment by elenanikiforova30031979** [comment]
созданы заново модель group с контроллерами для админа (crud) и вьюхи, и контроллер не админский с show, сиды

**Comment by elenanikiforova30031979** [comment]
связь установлена

**Comment by nirudef** [comment]
**Затраченное время:** 15 минут
