### ISSUE TITLE
#3 Создать ветку Dev

### ISSUE THREAD

**Issue by yuraefremov** [nirudef/as_crm#3]
**Конечный результат:**
Использование ветки Dev для тестовых решений 
**План  решения:**
Создаем ветку Dev. 

**Мотивация** :  Использование  Git Flow
**Критерий приемки:**
подключение  всех к ветке Dev

**Comment by elenanikiforova30031979** [comment]
ветка dev создана

**Comment by elenanikiforova30031979** [comment]
создано

**Comment by elenanikiforova30031979** [comment]
создана
