### ISSUE TITLE
Доступ в Админку имеет любой авторизованный пользователь

### ISSUE THREAD

**Issue by nirudef** [nirudef/as_crm#33]
**Шаги воспроизведения:**
Регистрируюсь, захожу на сайт как пользователь вообще без роли. Иду по адресу: admin/users
И вижу страницу, как будто я админ.

**Ожидаемое поведение:**
Меня должно было вернуть на главную страницу, потому что я не Админ.

**Причины:**
Не настроены уровни доступа к экшенам админа

**Вариант решения:**
Нужно добавить в Админ контроллер метод проверки текущего пользователя и позволять экшены, только если текущий пользователь - Админ

**Comment by Aseliya** [comment]
Время, затраченное на выполнение тикета - 15 минут
