### ISSUE TITLE
Доступ к профилю студента имеет любой даже незарегистрированный пользователь

### ISSUE THREAD

**Issue by nirudef** [nirudef/as_crm#34]
**Воспроизведение:**
Запускаю приложение.
Иду по адресу: http://localhost:3000/students/2
Вижу профиль студента.

**Ожидаемое поведение:** 
Нужно уточнить у Заказчика, но предполагаю, что профиль студента должен просматривать только сам студент.

**Причины:** 
не настроены уровни доступа к экшенам студента

**Вариант решения:**
Нужно добавить в Студент контроллер метод проверки текущего пользователя и разрешить экшены, и настроить доступ с учетом пожеланий Заказчика

**Comment by Aseliya** [comment]
Время, затраченное на завершение тикета 40 мин.
