### ISSUE TITLE
Enum для поля gender в таблицу студентов

### ISSUE THREAD

**Issue by nirudef** [nirudef/as_crm#36]
**Суть вопроса:**
В таблице студенты есть поле gender, тип которого integer
Предполагалось создать таблицу genders и оттуда подставлять значения в данное поле.
А надо ли создавать таблицу genders???

**Предложение:**
Прописать в модели Студент:
enum gender: {male: 0, female: 1}

**Мотивация:**
Храним в БД все также integer, но при визуализации получаем сразу значение.
К примеру, обратившись student.gender, получим значение male или female

**Comment by yuraefremov** [comment]
В таблице студентов нужно поле "Пол"  его возможно можно создать не только чекбоксом, но и радио баттан.
