### ISSUE TITLE
#4 Создание модели  User и подключение гема devise

### ISSUE THREAD

**Issue by yuraefremov** [nirudef/as_crm#4]
**Конечный результат**:  Создаем модель User и подключаем/настраиваем гем Devise

**План решения**:  Исходя из ТЗ: у нас будет несколько типов пользователей: Студент, Админ, Преподаватель, Саппорт.

Считаю, что реализовать это можно следующим образом:
Создаем модель User, которая будет иметь 3 поля: email, password, is_admin(boolean, default: false)
Эту модель подвязываем на Devise, который будет отвечать за авторизацию, подтверждение и восстановление пароля пользователя и т.д.

Как подключить и настроить гем, можно глянуть тут:
https://docs.google.com/document/d/19SnLL60ISwCIrrey3rPdRIH-FhUrEfLCPfPK83-KsKI/edit
Как в раздатке генерируем вьюхи только регистрации и логина

**Мотивация:** При таком подходе, у нас появится User, которую мы потом будем интегрировать с другими типами пользователей: Преподаватель, Студент и т.д.

**Критерий приемки**: Успешная регистрация и авторизация на сайте.

**Планируемое время работы:** 1 час

**Comment by nirudef** [comment]
Ответ Заказчика по вопросу предложенной реализации:

> Вроде правильно. Давайте я уточню. 
> Значит я захожу в систему под своей учеткой. Нажимаю кнопку создать студента или новый студент. Заполняю те поля которые мне нужны.
> Нажимаю кнопку создать и у меня на странице появляется в табличке строка, которая соответствует что у меня в системе появился студент. 
> В этой строке есть кнопка Экспортировать договор, но это отдельная фича.
> При этом студенту на почту пришла какая-то ссылка он на неё кликнул и отредактировал свой профиль в том числе свой пароль.
> Получается регистрация без генерирования паролей системой.
> В принципе такой вариант меня устроит.

**Comment by nirudef** [comment]
Создаем модели согласно приложенной схеме:

![image](https://user-images.githubusercontent.com/40805735/50895451-56472680-1430-11e9-92f2-6d8d63589510.png)

Дополнительно, при настройке Devise подключаем сразу :recoverable
Как? Смотрим в доке:
https://github.com/plataformatec/devise

**Comment by nirudef** [comment]
Свою идею реализовал в ветке Devise.
