### ISSUE TITLE
Поправить seed

### ISSUE THREAD

**Issue by yuraefremov** [nirudef/as_crm#45]
**Конечный результат**: Переписать  seed
**План решения:** Обновить seeds.rb  Добавить  данные для  созданных пользователей .
**Мотивация:**
Нужно чтобы все  поля были заполнены при прогонке.
**Критерий приемки:**
При прогонки seedов  проверяем всели сходится ? Т.е  можно ли зайти под  пользователем, все поля заполнены данными, отображаются ли данные

**Comment by Aseliya** [comment]
Необходимо актуализировать seed.rb, т.к. у нас появилось еще две сущности Группа и Курсы, которые связаны между собой, так же группа имеет связь с сущностью Студент.

**Comment by nirudef** [comment]
**Планируемое время работы:** 15 минут

**Comment by nirudef** [comment]
**Затраченное время:** 12 минут
