### ISSUE TITLE
Исправить процесс авторизации

### ISSUE THREAD

**Issue by Aseliya** [nirudef/as_crm#47]
**Конечный результат:**
Изменить процесс авторизации

**План решения:**
Настроить gem Devise на рассылку.
**Мотивация:**
Заказчик желает: при создании админом нового пользователя необходимо пользователю отправлять ссылку для авторизации на эл.почту, указанную при регистрации.
**Критерий приемки:**
Проверка процесса рассылки эл письма со ссылкой при заведении нового пользователя.

**Comment by nirudef** [comment]
Исходя из новых пожеланий Заказчика.
Механизм регистрации пользователей требует существенного изменения.
Для решения задачи, требуется также форма регистрации пользователя.

**Планируемое время работы:** 2 часа

**Comment by nirudef** [comment]
**Затраченное время:** 1 час 35 минут

Теперь механизм регистрации выглядит так:
Админ создает студента из админки.
После создания студента, в модели студента срабатывает метод создания пользователя:
````ruby
after_create :create_user

  private
  def create_user
    student = Student.last
    user = User.create!(email: student.email, role: 2)
  end
````
Для реализации задачи подключил фичу Devise :confirmable, которая позволяет отправить на почту пользователя письмо с инструкцией для подтверждения почты в таком виде:
![image](https://user-images.githubusercontent.com/40805735/51231083-73c64400-198c-11e9-98f4-fce7d453bf01.png)


После прохождения Пользователя по ссылке, на уровне девайса срабатывает метод:
````ruby
def after_confirmation_path_for(resource_name, resource)
    token = resource.send(:set_reset_password_token)
    edit_password_url(resource, reset_password_token: token)
  end
````
Который перенаправляет пользователя на страницу установки пароля и генерирует токен.
![image](https://user-images.githubusercontent.com/40805735/51231117-95273000-198c-11e9-970c-40c6d5e2f076.png)


Далее, пользователю остается лишь установить пароль и все.

**Comment by nirudef** [comment]
Еще, для того, чтобы работать с электронными письмами и не настраивать ActionMailer, я установил гем letter-opener
