### ISSUE TITLE
Исправить root страницу

### ISSUE THREAD

**Issue by Aseliya** [nirudef/as_crm#48]
**Конечный результат:**
Добавить на главную страницу форму авторизации.

**План решения:**
В контроллере welcome_controller создаем метод, выводящий форму авторизации.
**Мотивация:**
Заказчик желает: при открытии приложения первой страницей должно быть окно авторизации.
**Критерий приемки:**
Проверка наличия формы авторизации при входе в приложение.

**Comment by nirudef** [comment]
**Планируемое время работы:** 20 минут

**Comment by nirudef** [comment]
**Затраченное время:** 26 минут
