### ISSUE TITLE
#5  Возможность добавления студентов

### ISSUE THREAD

**Issue by yuraefremov** [nirudef/as_crm#5]

**Comment by yuraefremov** [comment]
**Конечный результат:** Студент логинется т.е вбивает пароль и  емаил свой.
**План решения**: Создаем сущность студен со всеми кредиталами  Имя студента
Фамилия
Курс
Группа
Телефон
Еще один телефон
Email
Скайп
Пол
Дата рождения
Паспортные данные
**Мотивация**: Заказщик хочет  использовать информацию о студенте для автоматического составления договора.
Критерий приемки: Нажимаем кнопкау логин ,  вводим пароль и емаил студента. Входим в общую  панель " О студенте"  . Нажимает  "Edit" вносим все изменения и заполняем все страницы  информации о студенте.

**Comment by elenanikiforova30031979** [comment]
не согласуется с каким-то gem/
