### ISSUE TITLE
Root страница для Admin панели

### ISSUE THREAD

**Issue by Aseliya** [nirudef/as_crm#52]
**Конечный результат:**
При входе в приложение через админа отображать полный список студентов.
**План решения:**
В роутинге прописать root страницу для админа через namespace.
**Мотивация:**
Главная страница админ панели содержит полный список студентов, т.е. root страница ссылается на students/index в админ панели.
**Критерий приемки:**
Проверка: при входе на http://localhost:3000/admin - видим полный список студентов.

**Comment by nirudef** [comment]
**Планируемое время работы:** 30 минут
