### ISSUE TITLE
Редактирование вьюхи Студенты для Админа

### ISSUE THREAD

**Issue by Aseliya** [nirudef/as_crm#53]
**Конечный результат:**
Таблица студентов должна быть без заголовков(типа Фамилия, Имя, ИИН и т д) и без столбца Отчество. Фамилия и Имя студента должны быть ссылкой на профиль студента.

**План решения:**
Создать вьюху admin/students/index.html.erb. Отображаем Фамилию и Имя в одном столбце, email, группу и Действия над записью(Показать, Редактировать, Удалить). На кнопку удаления пока можно поставить "заглушку". Остальные действия активные.
**Мотивация:**
Пожелание заказчика
**Критерий приемки:**
Проверка наличия вьюхи соответствующего содержания.

**Comment by nirudef** [comment]
**Планируемое время работы:** 30 минут

**Comment by nirudef** [comment]
**Затраченное время:** 28 минут
