### ISSUE TITLE
Подключение Active storage

### ISSUE THREAD

**Issue by Aseliya** [nirudef/as_crm#54]
Конечный результат: Подключить Active storage

План решения:
Можно следовать этим инструкциям:
http://rusrails.ru/active_storage_overview

Мотивация:
Заказчик при встрече попросил реализовать загрузку фото удостоверения личности и фото профиля с сохранением данных.

Критерии приемки:
Проверка наличия двух таблиц active_storage_attachments и active_storage_blobs в схеме миграции.

**Comment by elenanikiforova30031979** [comment]
примерное время выолнения 20 мин

**Comment by elenanikiforova30031979** [comment]
время выолнения 20 мин
 Подключен Active storage

**Comment by elenanikiforova30031979** [comment]
была ошибка при первом слиянии.(из тикета сразу в мастер)
