### ISSUE TITLE
Редактирование профиля студента

### ISSUE THREAD

**Issue by Aseliya** [nirudef/as_crm#55]
**Конечный результат:**
Профиль студента для админа должен содержать всю информацию о студенте.

**План решения:**
Во вьюхе admin/students/show.html.erb необходимо сделать правки кода. Расположить информацию о студенте необходимо по левому краю (визуально разделяя таблицу на две части в пропорции 3 к 2)
**Мотивация:**
Пожелание заказчика.
**Критерий приемки:**
Проверка наличия всей информации в профиле студента через админ панель.

**Comment by elenanikiforova30031979** [comment]
#55 Во вьюхе admin/students/show.html.erb  сделано расположение  информации о студенте, установлен activestorage(54 ticket, раположение фото не установлено.
завтра доделать

**Comment by nirudef** [comment]
Коллеги, давайте сразу украсим, стиле подцепим... Бутстрап же есть...
Можно вывести списком, к примеру:
http://bootstrap-4.ru/docs/4.1/components/list-group/

А экран делить не визуально, в выделить под список col-sm-3 т.е. ширина будет - 3 столбца. 
Кто что думает?

Елена, я бы заменил picture на avatar.
Т.е. нужно помнить, Админ будет смотреть сканы удоса, а Студент в своем профиле может прикрепить аватарку. Поэтому ему мы отображаем avatar, согласны?

**Comment by Aseliya** [comment]
Игорь,вот именно что визуальное деление. А как там будет в коде это на усмотрение разраба.

**Comment by nirudef** [comment]
Согласен, но вот так однозначно плохо:
![image](https://user-images.githubusercontent.com/40805735/51469603-e758be80-1d9b-11e9-9e52-a37dabe194a5.png)

Елена, надо же уточнять как делать, если есть вопросы...

**Comment by nirudef** [comment]
Ни деления, ни стилей, ни инициативы - ничего нет!

**Comment by elenanikiforova30031979** [comment]
я же его еще не доделала, ИГОРЬ
