### ISSUE TITLE
#6  Root страница

### ISSUE THREAD

**Issue by nirudef** [nirudef/as_crm#6]
**Конечный результат:** Создаем root страницу

**План решения:**
Нужно определиться что у нас будет Главной страницей проекта.
Предлагаю пока создать контроллер типа welcome и в нем создать index
Соответственно создает вьюху: welcome/index

**Мотивация:**
gem Devise при настройки требует указать Главную страницу, куда он будет редиректить юзера при выходе из системы.
В ТЗ нет указаний про какие-либо статические страницы, поэтому надо бы уточнить данный вопрос у Заказчика. 

**Критерии приемки:** при переходе на url сайта попадаем на главную страницу.

**Планируемое время работы:** 20 минут

**Comment by elenanikiforova30031979** [comment]
планируемое время работы 40 минут

**Comment by elenanikiforova30031979** [comment]
готово

**Comment by nirudef** [comment]
Нет результата в репозитории.
