### ISSUE TITLE
Отображение логотипа

### ISSUE THREAD

**Issue by Aseliya** [nirudef/as_crm#61]
**Шаги воспроизведения**
Захожу на главную страницу.
**Наблюдаемое поведение:**
Логотип не отображается на главной странице.
**Ожидаемое поведение:** 
С формой "Войти" на главной странице приложения должен отображаться логотип организации.
**Причины:** 
Проблема в использовании абсолютного url для тега изображения.
**Вариант решения:**
Создать папку uploads (в public), сохранить логотип в данной папке. Прописать путь во вьюхе к данному изображению.

**Comment by nirudef** [comment]
**Планируемое время работы:** 10 минут
