### ISSUE TITLE
Создание модели Преподаватели

### ISSUE THREAD

**Issue by Aseliya** [nirudef/as_crm#62]
**Конечный результат:**
Создать модель Teacher

**План решения:**
Генерируем модель Teacher с полями: Ф.И.О., email, телефон, телефон 2, Telegram
Устанавливаем связь с моделью Group
делаем CRUD для Админа
Создаем контроллер admin/teachers_controller
Настраиваем роутинг для админа

**Мотивация:**
У группы студентов имеется преподаватель.

**Критерий приемки:**
Проверка таблицы Преподаватели

**Comment by yuraefremov** [comment]
сделал примерно за 1 час 20 минут

**Comment by nirudef** [comment]
Про связь не уверен, а в остальном - все супер!

**Comment by yuraefremov** [comment]
к Сидам для проверки добавить  надо : 1.times do |i|
  i = Teacher.create!(
  first_name: 'Уэлс',
  last_name: 'Герберт',
  middle_name: 'Андреевич',
  tel_1: '87775878787',
  tel_2: '87775454548',
  email: 'gerberd@gmail',
  telegram: 'gerberd1112232',
  group_id: 1)

  i.picture.attach(
    io:File.open("app/assets/images/#{i.id}.jpeg"),
    filename: "{i.id}.jpeg")
end

**Comment by Aseliya** [comment]
Доработать связь между сущностями Teacher и Group, прописать в данных моделях хелперы.
