### ISSUE TITLE
Редактирование поля Gender в форме добавления Студента

### ISSUE THREAD

**Issue by Aseliya** [nirudef/as_crm#69]
**Конечный результат:**
В форме добавления студента выпадающее окно с выбором пола(М, Ж) студента.

**План решения:**
Прописать в модели Студент:
enum gender: {male: 0, female: 1}.
Сделать правки в partial admin/students/_form.html.erb.
Подробнее ознакомиться с инструментом и его применением можно https://www.justinweiss.com/articles/creating-easy-readable-attributes-with-activerecord-enums/

**Мотивация**:
У студента при добавлении должен определяться пол.

**Критерий приемки:**
Наличие в форме добавления нового студента значения "Пол" (М, Ж).

**Comment by elenanikiforova30031979** [comment]
примерное время выполнения 1 час

**Comment by elenanikiforova30031979** [comment]
выполнено за 30 мин

**Comment by nirudef** [comment]
Я это вижу так:
Ключи пишем на англ:
![image](https://user-images.githubusercontent.com/40805735/51523153-39a9e600-1e55-11e9-9f12-611f06bbad5b.png)

Добавляем стили сразу в форму:
![image](https://user-images.githubusercontent.com/40805735/51523187-50503d00-1e55-11e9-8ebc-3560625c6611.png)

В итоге получаем вот такой результат в форме:
![image](https://user-images.githubusercontent.com/40805735/51523233-6a8a1b00-1e55-11e9-8f6d-4ff812d3ab0c.png)

На уровне базы данных у нас будет так:
![image](https://user-images.githubusercontent.com/40805735/51523301-973e3280-1e55-11e9-9e87-f611b0a667e4.png)

А в консоле мы видем так:
![image](https://user-images.githubusercontent.com/40805735/51523415-d2406600-1e55-11e9-98ca-b09a9151ca42.png)
