### ISSUE TITLE
Создать навигационную панель для Админа

### ISSUE THREAD

**Issue by Aseliya** [nirudef/as_crm#75]
**Конечный результат:**
В навбаре кабинета Админа создать выпадающие меню "Просмотр"(со вкладками Студентов/Групп/Курсов/Преподавателей), "Добавить"(со вкладками Студента/Группу/Курс/Преподавателя)

**План решения:**
Прописать в views/layouts/admin.html.erb ссылки на вьюхи index, new Студентов, Преподавателей, Групп, Курсов. При необходимости недостающие вьюхи создать(в views/admin/(сущность), сделать необходимые правки кода для вывода полного списка и формы создания нового экземпляра. При необходимости внести правки в соответствующие контроллеры.

**Мотивация:**
Упростить навигацию для Админа

**Критерий приемки:**
Проверка наличия в навбаре навигационной панели с выпадающим меню.

**Comment by nirudef** [comment]
**Планируемое время работы:** 30 минут

**Comment by nirudef** [comment]
**Затраченное время:** 1 час 45 минут
Пришлось добавить вьюхи, экшены и стили формам.

**Comment by Aseliya** [comment]
> **Затраченное время:** 1 час 45 минут
> Пришлось добавить вьюхи, экшены и стили формам.

В тикете прописано что придется это делать. Я предвидела. :+1:
