### ISSUE TITLE
Изменить поле skype на поле telegram , убрать лишнее поле course_id в модели Студент

### ISSUE THREAD

**Issue by Aseliya** [nirudef/as_crm#77]
**Конечный результат:**
В форме заведения нового студента отсутствует поле Курс, Skype изменен на данные Telegram
**План решения:**
Изменить поля во вьюхах

**Мотивация:**
Требование заказчика: желает видеть Telegram студента,курс может узнать по группе, в которой будет обучаться студент.

**Критерий приемки:**
Проверка отсутствия в модели Студенты course_id, skype полей.

**Comment by elenanikiforova30031979** [comment]
примерное время выполнения : 30 мин

**Comment by elenanikiforova30031979** [comment]
выолнено за 40 мин

**Comment by nirudef** [comment]
Елена, рано клеить лейбл Done, course_id не удален, Telegram надо сделать с маленькой буквы, потому что при создании таблицы рельсы скорее всего сделают его с маленькой буквы, а в сидах у вас с большой... И на мой взгляд, лучше сделать это отдельной миграцией, а не поправлять предыдущую

**Comment by nirudef** [comment]
Елена, лучше создать новую миграцию, чем править предыдущую...
Вот проблема, с которой мы можем столкнуться при вашем решении
https://stackoverflow.com/questions/1416600/rails-i-update-migration-file-then-run-dbmigrate-but-my-schema-isnt-updating
Там также рекомендуют вносить изменения новой миграцией.
