### ISSUE TITLE
Внесение изменений в страницы просмотра и редактирования Групп и Курсов

### ISSUE THREAD

**Issue by elenanikiforova30031979** [nirudef/as_crm#92]
Конечный результат:
Уменьшить длину строк в страницах просмотра и редактирования Групп и Курсов,  вместо кнопок "удалить" и "редактировать" вставить иконки, при клике на дату курса должен выходить календарь

План решения:
Исправить код во  вьюхах:  admin/groups/index  ,  admin/groups/_form...,  admin/courses/index , admin/courses/_form/html.erb
Мотивация:
Желание заказчика
Критерий приемки:
Проверка наличия изменненых длин строк, календаря, иконокок

**Comment by Aseliya** [comment]
Исправление форм: 30 минут.
Подключение гема и настройка иконок: 40 минут

**Comment by Aseliya** [comment]
Затраченное время:1 час 30 минут
