### ISSUE TITLE
Создание модели Занятие

### ISSUE THREAD

**Issue by elenanikiforova30031979** [nirudef/as_crm#95]
Конечный результат:
Создать модель Lesson

План решения:
Генерируем модель Lesson с полями
program_id:integer
date:date
groupe_id:integer
Устанавливаем связь с моделью  Program (один ко многим) Lessons
делаем CRUD для Админа
Создаем контроллер admin/lessons_controller
Создаем вьюхи admin(index, show, edit, update, delete)
Настраиваем роутинг для админа

Мотивация:
необходимость наличия Занятий у студентов определенной группы

Критерий приемки:
Проверка таблицы, создание занятий, проверка  наличия занятия

**Comment by nirudef** [comment]
**Планируемое время работы:** 40 минут

**Comment by nirudef** [comment]
**Затраченное время:** 35 минут
