### ISSUE TITLE
Создание модели Программа курса (program) 

### ISSUE THREAD

**Issue by elenanikiforova30031979** [nirudef/as_crm#99]
Конечный результат:
Создать модель Program

План решения:
Генерируем модель Program с полями

number:integer
name:string
handout:binary
homework:binary
addition;binary

Устанавливаем связь с моделью Course(1k1)
делаем CRUD для Админа
Создаем контроллер admin/programs_controller
Создаем вьюхи admin(index, show, edit, update, delete)
Настраиваем роутинг для админа

Мотивация:
необходимость просмотра наличия Программы курса  у определенного Курса

Критерий приемки:
Проверка таблицы, создание Программы курса

**Comment by nirudef** [comment]
**Планируемое время работы:** 30 минут
